apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    upstream backend {
        server app-1-svc:80;
        server app-2-svc:80;
    }

    server {
        location /nginx {
            proxy_pass http://backend;
        }
    }
