apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    upstream backend {
        server app-1-svc;
        server app-2-svc;
    }
    server {
        location / {
            proxy_pass http://backend;
        }
    }
